# Generated by Django 6.0.4 on 2026-04-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_model', models.CharField(max_length=120)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('type', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('assigned', 'Выдан'), ('maintenance', 'На обслуживании')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand_model', 'vin'],
                'indexes': [models.Index(fields=['status'], name='fleet_car_status_d0b34f_idx'), models.Index(fields=['vin'], name='fleet_car_vin_bd279d_idx')],
            },
        ),
    ]
