# Generated by Codex on 2026-04-26

import datetime

import django.conf
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
        ("requests", "0002_request_return_defects"),
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("repair", "Ремонт"), ("service", "ТО")],
                        max_length=20,
                    ),
                ),
                ("service_date", models.DateField(default=datetime.date.today)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("contractor", models.CharField(blank=True, max_length=120)),
                ("mileage", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="fleet.car",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_records_created",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_records",
                        to="requests.request",
                    ),
                ),
            ],
            options={
                "ordering": ["-service_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["car", "service_date"],
                        name="fleet_maint_car_id_fe8624_idx",
                    ),
                    models.Index(fields=["kind"], name="fleet_maint_kind_10b04b_idx"),
                ],
            },
        ),
    ]
