# Generated by Django 6.0.4 on 2026-04-09 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fleet', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='fleet.car')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='accounts.employee')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='requests.request')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['start_date'], name='reports_rep_start_d_c9cca1_idx'), models.Index(fields=['end_date'], name='reports_rep_end_dat_90a626_idx')],
            },
        ),
    ]
