# Generated by Django 6.0.4 on 2026-04-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='return_defects',
            field=models.TextField(blank=True),
        ),
    ]
