# Generated by Codex on 2026-04-26

from django.db import migrations, models

import requests.models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0002_request_return_defects"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="attachment",
            field=models.FileField(
                blank=True, upload_to=requests.models.request_attachment_upload_to
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="attachment_original_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="request",
            name="rules_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="request",
            name="rules_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
